version: "3"

services:
  web:
    image: nginx
    ports:
      - "8080:80" # port_localhost: port_container
    volumes:
      - ./web:/usr/share/nginx/html
  back:
    build: .
    ports:
      - "3131:3000"
