version: "3"

services:
  frontend:
    build:
      context: ./frontend
      args:
        PORT: "3000"
    ports:
      - "3005:3000" # port_localhost: port_container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      args:
        PORT: "5555"
    ports:
      - "3006:5555"
    environment:
      PORT: 5555
